encoding: utf-8
author: yxp
title: yxp的博客
github_site: https://github.com/yxping
weibo_site: https://weibo.com/yaoxiaopengweibo

# 开启分页功能
paginate: 10

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# output dir
destination: public

# source dir
source: src

# exlude this file or dir
exlude: ['node_modules', gulpfile.js]

# baseurl: /src
